version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
      - microservices
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    networks:
      - microservices
    ports:
      - 8081:8081

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - microservices
    ports:
      - '9090:9090'
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - microservices
    ports:
      - 5341:80

  grafana: 
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - microservices
    ports:
      - 3000:3000

  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - microservices

  # influxdb:
  #   image: quay.io/influxdb/influxdb:v2.0.3
  #   container_name: influxdb
  #   restart: unless-stopped
  #   ports:
  #     - "8086:8086"
  #   networks:
  #   - microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservices

networks:
  microservices:
    name: microservices-network