FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/prometheus.yml
ADD ./prometheus.yml /etc/prometheus/prometheus.yml
ADD ./prometheus/prometheus.yml /etc/prometheus/prometheus.yml

COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY ./prometheus.yml /etc/prometheus/prometheus.yml
COPY ./prometheus/prometheus.yml /etc/prometheus/prometheus.yml