### 
### Variables
###
@schema = http
@hostname = localhost
@port = 5010
@host = {{schema}}://{{hostname}}:{{port}}

###
### Service is running
###
GET {{host}}

###
### Create comment
###
# @name add_comment
POST {{host}}/api/v1/comments
Content-Type: application/json

{
  "userId": "f2e62a55-ce09-4a6d-9212-237d462aa137",
  "postId": "f2e62a55-ce09-4a6d-9212-237d462aa137",
  "content": "test-content"
}

###
### Get comment
###
GET {{host}}/{{add_comment.response.headers.Location}}

###
### Get comments
###
GET {{host}}/api/v1/comments?postId=f2e62a55-ce09-4a6d-9210-237d462aa137